# 数组基本运算

In [1]:
from numpy import *

In [6]:
import numpy
import numpy as np

print array([1, 2, 3, 4])
print numpy.array([1, 2, 3, 4])   
print np.array([1, 2, 3, 4])        # 这三句话是一样的意思

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [8]:
a = array([1, 2, 3, 4])
b = arange(4)

print a + b
print a - b
print a * b
print a ** 2
print a < 2

[1 3 5 7]
[1 1 1 1]
[ 0  2  6 12]
[ 1  4  9 16]
[ True False False False]


In [10]:
c = array([[1, 1], [0, 1]])
d = array([[2, 0], [3, 4]])

print 'c*d:', c*d
print 'dot(c, d):', dot(c, d)

c*d: [[2 0]
 [0 4]]
dot(c, d): [[5 4]
 [3 4]]


In [12]:
e = ones((2, 3), dtype = int)
e *= 3

print e



[[3 3 3]
 [3 3 3]]


In [13]:
f = random.random((2, 3))
print f

f += e
print f

[[ 0.99922907  0.6633736   0.73823856]
 [ 0.27988815  0.67706023  0.79480409]]
[[ 3.99922907  3.6633736   3.73823856]
 [ 3.27988815  3.67706023  3.79480409]]


In [19]:
g = linspace(1, 10, 10) # 创建一个一维数组，并且是等差数列构成的一维数组,第三个参数是元素个数，与arange()函数第三个参数表示的步长不同
print 'g:', g
print g.dtype

print linspace(1, 10, 10, endpoint = False)  # endpoint表示是否包含终止值，默认是True

g: [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
float64
[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1]


In [22]:
print f.sum()
print f.min()
print f.max()

22.1525937056
3.27988814805
3.99922907451


## axis 应用到数组指定的轴上

In [23]:
h = arange(12).reshape(3, 4)      #axis总共有2个 故取值为axis = 0 或者 1
print 'h:', h

h.sum(axis = 0)    # 每列的和

h: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [25]:
print h.min()
print h.min(axis = 1)   #每行的最小值

0
[0 4 8]


In [26]:
print h.cumsum()
print h.cumsum(axis = 1)

[ 0  1  3  6 10 15 21 28 36 45 55 66]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


# 形状操作

In [27]:
i = floor(10 * random.random((3, 4)))
print 'i:', i

i: [[ 5.  2.  6.  2.]
 [ 4.  4.  4.  0.]
 [ 6.  4.  7.  2.]]


In [28]:
print i.shape

(3, 4)


In [30]:
i.ravel()  # flattern the array

array([ 5.,  2.,  6.,  2.,  4.,  4.,  4.,  0.,  6.,  4.,  7.,  2.])

In [31]:
i.shape = (6, 2)
i.transpose()

array([[ 5.,  6.,  4.,  4.,  6.,  7.],
       [ 2.,  2.,  4.,  0.,  4.,  2.]])

In [33]:
print i.shape

(6, 2)
